window.BB = Backbone;

BB.globs = {};
BB.SERVICES = {};
BB.EVENTS = {};
BB.LOADING = {};
BB.CONSTS = {};
BB.EVENTS = {};

// services
BB.SERVICES.SAMPLE_VIEW = 'SAMPLE_VIEW';
BB.SERVICES.LOADING_VIEW = 'LOADING_VIEW';

// events
BB.EVENTS.APP_STACK_VIEW = 'APP_STACK_VIEW';
BB.EVENTS.ON_XMLDATA = 'ON_XMLDATA';
BB.EVENTS.ON_XMLDATA_ERROR = 'ON_XMLDATA_ERROR';
BB.EVENTS.ON_PLAYER_EVENT = 'ON_PLAYER_EVENT';
BB.EVENTS.ON_DISPOSE = 'ON_DISPOSE';

